[package]
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
name = "achordion-eurorack"
version = "0.2.0" # hack/release.sh
license = "GPL-3.0-or-later"
description = "Chord-crafting quantizing wavetable oscillator module for Eurorack"
repository = "https://github.com/zlosynth/achordion"
readme = "../README.md"
publish = false

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
cortex-m-rtic = "0.5.6"
cortex-m-semihosting = "0.3"
panic-halt = "0.2.0"
typenum = "1"
lazy_static = { version = "1.4", features = [ "spin_no_std" ] }
achordion-lib = { path = "../lib" }
stm32_i2s_v12x = "0.2"

[dependencies.stm32f4xx-hal]
features = ["stm32f407", "rt", "i2s", "usb_fs"]
git = "https://github.com/stm32-rs/stm32f4xx-hal"
rev = "7ccd36028c474617c052c7a45c57b379c7bdf1a2"

[[bin]]
name = "achordion-eurorack"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
