[package]
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
name = "achordion-eurorack"
version = "0.7.0" # hack/release.sh
license = "GPL-3.0-or-later"
description = "Chord-crafting quantizing wavetable oscillator module for Eurorack."
repository = "https://github.com/zlosynth/achordion"
readme = "../README.md"
publish = false

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
cortex-m-rtic = "0.5.6"
cortex-m-semihosting = "0.3"
stm32h7xx-hal = { version = "0.9.0", features = [ "stm32h750v", "rt", "revision_v" ] }
panic-halt = "0.2.0"
typenum = "1"
lazy_static = { version = "1.4", features = [ "spin_no_std" ] }
achordion-lib = { path = "../lib" }
micromath = "1.1"

[dependencies.daisy_bsp]
git = "https://github.com/phoracek/daisy_bsp"
rev = "76b195eb441005eac33033e6ad3de1f024ec4940"

[[bin]]
name = "achordion-eurorack"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on flash
lto = true # better optimizations
opt-level = 2 # code with level 3 won't fit on flash
