[package]
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
name = "achordion-eurorack"
version = "0.10.0" # hack/release.sh
license = "GPL-3.0-or-later"
description = "Chord-crafting quantizing wavetable oscillator module for Eurorack."
repository = "https://github.com/zlosynth/achordion"
readme = "../README.md"
publish = false

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
cortex-m-rtic = "0.5.6"
cortex-m-semihosting = "0.3"
panic-halt = "0.2.0"
typenum = "1"
lazy_static = { version = "1.4", features = [ "spin_no_std" ] }
achordion-lib = { path = "../lib" }
micromath = "1.1"
nb = "1"

# Requires custom branch with QSPI and split ADC
[dependencies.stm32h7xx-hal]
git = "https://github.com/phoracek/stm32h7xx-hal"
branch = "async_adc_stable"
features = [ "stm32h750v", "rt", "revision_v" ]

# Requires custom branch with QSPI and split ADC
[dependencies.daisy_bsp]
git = "https://github.com/phoracek/daisy_bsp"
rev = "99dcd44b16f1b619996e2546e9c56c47341e5364"

[[bin]]
name = "achordion-eurorack"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on flash
lto = true # better optimizations
opt-level = "s" # code with higher optimization won't fit flash
