[package]
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
name = "achordion"
version = "0.1.0"
license = "GPL-3.0-or-later"
description = "Work in progress"
repository = "https://github.com/zlosynth/achordion"
readme = "../README.md"
publish = false

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
cortex-m-rtic = "0.5.6"
cortex-m-semihosting = "0.3"
panic-halt = "0.2.0"
typenum = "1"
lazy_static = { version = "1.4", features = [ "spin_no_std" ] }
achordion-lib = { path = "../lib" }
stm32_i2s_v12x = "0.2"
usb-device = "0.2.5"

[dependencies.stm32f4xx-hal]
features = ["stm32f407", "rt", "i2s", "usb_fs"]
git = "https://github.com/samcrow/stm32f4xx-hal"
rev = "da0d5ba77c4a4d4a41bab2b86cdffb40f396d40d"

[dependencies.usbd-midi]
git = "https://github.com/btrepp/usbd-midi"
rev = "49484f0b157c61818149fe6ef17ea5183dddef04"

[[bin]]
name = "achordion"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
