[package]
name = "achordion-pd"
version = "0.0.1"
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
pd-sys = "0.1.0"
achordion-lib = { path = "../lib" }
field-offset = "0.3"
lazy_static = "1.4"
