name: Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-all:
    name: Check all
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install x86 Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          default: true
          override: true
          components: rustfmt, clippy
      - name: Install ARM Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: thumbv7em-none-eabihf
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Check formatting
        run: make check-format
      - name: Check clippy
        run: make clippy
      - name: Check compilation
        run: make check
      - name: Run tests
        run: make test
